"""Write committed outputs: platform-level aggregates only (no raw rows)."""

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import pandas as pd  # noqa: E402

from analyses.posting_lifespan.extract import LIFESPAN_SQL, MIN_FIRST_SEEN  # noqa: E402
from analyses.posting_lifespan.survival import SURVIVAL_GRID_DAYS  # noqa: E402

CAVEATS = """
- Clock is scanner observation (`first_seen` -> `last_seen`), not employer posting
  date (`posted_date` is only ~34% populated). Lifespans are bounded by scan
  cadence; sub-day resolution is not meaningful.
- Corpus is a single owner's tracked query set (tech/data-skewed), not a random
  sample of the job market. Claims are scoped to tracked platforms/companies.
- Platform attribution is company-level ATS assignment; jobs from companies with
  no attributed ATS (see exclusion accounting) are excluded from strata.
- `expired` detection has lag: a posting is confirmed dead at the check AFTER it
  died. Median estimates are upper-bound-biased by up to one scan interval.
- Right-censoring share per stratum is visible in the Results table (n - events).
""".strip()


def _rows(results: dict[str, dict], variant: str) -> list[dict]:
    rows = []
    for platform, stats in sorted(results.items()):
        row = {
            "variant": variant,
            "platform": platform,
            "n": stats["n"],
            "events": stats["events"],
            "median_days": stats["median_days"],
        }
        for d in SURVIVAL_GRID_DAYS:
            row[f"s{d}"] = stats["survival"][d]
        rows.append(row)
    return rows


def _figure(primary: dict[str, dict], path: Path) -> None:
    fig, ax = plt.subplots(figsize=(8, 5))
    platforms = [p for p in primary if p != "ALL"]
    for platform in sorted(platforms):
        s = primary[platform]["survival"]
        xs = [0] + SURVIVAL_GRID_DAYS
        ys = [1.0] + [s[d] for d in SURVIVAL_GRID_DAYS]
        ax.step(xs, ys, where="post", label=f"{platform} (n={primary[platform]['n']})")
    ax.set_xlabel("days since first seen")
    ax.set_ylabel("share of postings still alive")
    ax.set_title("Job-posting survival by ATS platform (Kaplan-Meier)")
    ax.set_ylim(0, 1)
    ax.legend()
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)


def _numbers_md(primary, robustness, exclusions) -> str:
    results_table = pd.DataFrame(_rows(primary, "primary")).to_markdown(index=False)
    robustness_table = pd.DataFrame(_rows(robustness, "inconclusive_as_censored")).to_markdown(
        index=False
    )
    exclusion_lines = "\n".join(f"- {k}: {v:,}" for k, v in exclusions.items())
    sql = LIFESPAN_SQL.format(statuses="'live', 'expired'")
    return f"""# Posting lifespan by ATS platform - verified numbers

All numbers below are machine-generated by `run.py`. Interpretation is written
by the owner only (founder-authorship plank).

## Headline

Overall median observed lifespan: **{primary["ALL"]["median_days"]:.1f} days**
(n={primary["ALL"]["n"]:,}, observed expirations={primary["ALL"]["events"]:,}).

## Exclusion accounting

{exclusion_lines}

## Method

Kaplan-Meier right-censored survival. Event = `expiry_status='expired'`;
censored = `'live'`; `inconclusive`/NULL excluded from primary (see Robustness).
Strata floor: platforms with n < 200 are folded into ALL only.
Data-quality filters: `first_seen > '{MIN_FIRST_SEEN}'`, `last_seen >= first_seen`.

## Results

{results_table}

## Robustness

Variant treating `inconclusive` as censored:

{robustness_table}

## Caveats

{CAVEATS}

## SQL appendix

```sql
{sql}
```
"""


def write_outputs(primary, robustness, exclusions, outdir: Path) -> None:
    outdir.mkdir(parents=True, exist_ok=True)
    (outdir / "figures").mkdir(exist_ok=True)
    all_rows = _rows(primary, "primary") + _rows(robustness, "inconclusive_as_censored")
    pd.DataFrame(all_rows).to_csv(outdir / "aggregates.csv", index=False)
    _figure(primary, outdir / "figures" / "km_by_platform.png")
    (outdir / "NUMBERS.md").write_text(
        _numbers_md(primary, robustness, exclusions), encoding="utf-8", newline="\n"
    )
